### ISSUE TITLE
Error installing with vite 3.0.7

### ISSUE THREAD

**Issue by markusand** [Modyfi/vite-plugin-yaml#6] opened 2022-08-14 18:52 UTC
I updated some dependencies and this plugin seems not to support Vite 3.0.7, although supposedly hould be supported ^3.0.0.
Using --force flag works, but this should not be the solution.

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: command@0.0.0
npm ERR! Found: vite@3.0.7
npm ERR! node_modules/vite
npm ERR!   dev vite@"^3.0.7" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^2.6.0" from @modyfi/vite-plugin-yaml@1.0.2
npm ERR! node_modules/@modyfi/vite-plugin-yaml
npm ERR!   dev @modyfi/vite-plugin-yaml@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by tonyketcham** [comment] 2022-08-14 20:18
I just published the latest version which support for Vite 3.x was added. Please update to `v1.0.3`!

Closing as duplicate of #4

**Closed by tonyketcham** 2022-08-14 20:18 UTC
